#Build-environment configuration
sudo: required
dist: trusty

#Get the latests chrome version
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

#Specify Python versions
language: python
python:
  - "3.6"
#Install preconditions
install:
  - pip install -r requirements.txt
#Run the unit_tests
script:
  - coverage run --source=pytholenium /home/travis/build/ArgiesDario/pytholenium/pytholenium/unit_tests.py

#Get the chromedriver x64 for linux (version 2.42), put it in path with permissions
before_script:
  - wget chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/build/ArgiesDario/pytholenium/pytholenium/test_data
  - sudo chmod 777 /home/travis/build/ArgiesDario/pytholenium/pytholenium/test_data/chromedriver
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5

after_success:
  coveralls
