sudo: required
dist: trusty

addons:
  chrome: stable

language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python pytholenium/unit_tests.py

before_script:
  - wget chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/build/ArgiesDario/pytholenium/pytholenium/test_data
  - sudo chmod 777 /home/travis/build/ArgiesDario/pytholenium/pytholenium/test_data/chromedriver_v2.42.exe
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5
